2023-03-28 15:51:35.701 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-03-28 15:51:42.288 | ERROR    | services.explorer.explorer:get_order_history:142 - Failed to get order history, cookie may have expired
Traceback (most recent call last):
  File "/home/runner/work/apic/apic/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/apic/apic/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/apic/apic/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/apic/apic/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 301, in run
    promotions = self.preload()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 269, in preload
    self.ph.get_oder_history(ctx_cookies=self._ctx_cookies)
  File "/home/runner/work/apic/apic/epic/src/services/explorer/explorer.py", line 219, in get_oder_history
    if resp := explorer.get_order_history(ctx_cookies):
> File "/home/runner/work/apic/apic/epic/src/services/explorer/explorer.py", line 140, in get_order_history
    raise RequestException("Failed to get order history, cookie may have expired")
requests.exceptions.RequestException: Failed to get order history, cookie may have expired
2023-03-28 15:52:25.383 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1773), thread 'MainThread' (139766803319680):
Traceback (most recent call last):
  File "/home/runner/work/apic/apic/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/apic/apic/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/apic/apic/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/apic/apic/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/core.py", line 557, in cart_handle_payment
    if self._click_order_button(page):  # cart_handle_payment
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/core.py", line 456, in _click_order_button
    payment_btn.click()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13519, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//div[@id='webPurchaseContainer']//iframe"
============================================================
2023-03-31 07:26:47.525 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-03-31 07:26:52.356 | ERROR    | services.explorer.explorer:get_order_history:142 - Failed to get order history, cookie may have expired
Traceback (most recent call last):
  File "/home/runner/work/apic/apic/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/apic/apic/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/apic/apic/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/apic/apic/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 301, in run
    promotions = self.preload()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 269, in preload
    self.ph.get_oder_history(ctx_cookies=self._ctx_cookies)
  File "/home/runner/work/apic/apic/epic/src/services/explorer/explorer.py", line 219, in get_oder_history
    if resp := explorer.get_order_history(ctx_cookies):
> File "/home/runner/work/apic/apic/epic/src/services/explorer/explorer.py", line 140, in get_order_history
    raise RequestException("Failed to get order history, cookie may have expired")
requests.exceptions.RequestException: Failed to get order history, cookie may have expired
2023-03-31 07:27:30.260 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1805), thread 'MainThread' (140566175829056):
Traceback (most recent call last):
  File "/home/runner/work/apic/apic/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/apic/apic/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/apic/apic/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/apic/apic/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/core.py", line 557, in cart_handle_payment
    if self._click_order_button(page):  # cart_handle_payment
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/core.py", line 456, in _click_order_button
    payment_btn.click()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13519, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//div[@id='webPurchaseContainer']//iframe"
============================================================
2023-04-01 07:26:41.803 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-04-01 07:26:48.390 | ERROR    | services.explorer.explorer:get_order_history:142 - Failed to get order history, cookie may have expired
Traceback (most recent call last):
  File "/home/runner/work/apic/apic/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/apic/apic/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/apic/apic/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/apic/apic/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 301, in run
    promotions = self.preload()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 269, in preload
    self.ph.get_oder_history(ctx_cookies=self._ctx_cookies)
  File "/home/runner/work/apic/apic/epic/src/services/explorer/explorer.py", line 219, in get_oder_history
    if resp := explorer.get_order_history(ctx_cookies):
> File "/home/runner/work/apic/apic/epic/src/services/explorer/explorer.py", line 140, in get_order_history
    raise RequestException("Failed to get order history, cookie may have expired")
requests.exceptions.RequestException: Failed to get order history, cookie may have expired
2023-04-01 07:27:28.543 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1815), thread 'MainThread' (140201636318080):
Traceback (most recent call last):
  File "/home/runner/work/apic/apic/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/apic/apic/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/apic/apic/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/apic/apic/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/core.py", line 557, in cart_handle_payment
    if self._click_order_button(page):  # cart_handle_payment
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/core.py", line 456, in _click_order_button
    payment_btn.click()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13519, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//div[@id='webPurchaseContainer']//iframe"
============================================================
2023-04-07 07:25:53.024 | CRITICAL | services.bricklayer.core:refresh_ctx_cookies:717 - >> MISS [CookieManager] Identity token update failed
2023-04-07 07:25:58.680 | ERROR    | services.explorer.explorer:get_order_history:142 - Failed to get order history, cookie may have expired
Traceback (most recent call last):
  File "/home/runner/work/apic/apic/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/apic/apic/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/apic/apic/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/apic/apic/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 301, in run
    promotions = self.preload()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 269, in preload
    self.ph.get_oder_history(ctx_cookies=self._ctx_cookies)
  File "/home/runner/work/apic/apic/epic/src/services/explorer/explorer.py", line 219, in get_oder_history
    if resp := explorer.get_order_history(ctx_cookies):
> File "/home/runner/work/apic/apic/epic/src/services/explorer/explorer.py", line 140, in get_order_history
    raise RequestException("Failed to get order history, cookie may have expired")
requests.exceptions.RequestException: Failed to get order history, cookie may have expired
2023-04-07 07:26:41.754 | ERROR    | services.scaffold:claim:138 - An error has been caught in function 'claim', process 'MainProcess' (1804), thread 'MainThread' (139965863332736):
Traceback (most recent call last):
  File "/home/runner/work/apic/apic/epic/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/home/runner/work/apic/apic/epic/src/services/scaffold.py", line 138, in claim
    claimer.run(silence=silence, log_ignore=ignore, unreal=unreal)
  File "/home/runner/work/apic/apic/epic/src/apis/scaffold/claimer.py", line 26, in run
    ClaimerScheduler(silence=silence, unreal=unreal).job_loop_claim(log_ignore)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 112, in job_loop_claim
    claimer.just_do_it()
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 309, in just_do_it
    fire(
  File "/home/runner/work/apic/apic/epic/src/services/utils/toolbox.py", line 84, in fire
    container(context)
  File "/home/runner/work/apic/apic/epic/src/services/deploy.py", line 305, in run
    result = empower_games_claimer(self.bricklayer, promotion.url, page, pattern="get")
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/game.py", line 170, in empower_games_claimer
    return claimer.get_free_game(page_link=page_link, page=page, pattern=pattern)
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/game.py", line 157, in get_free_game
    self.cart_handle_payment(page)  # mode: get
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/core.py", line 557, in cart_handle_payment
    if self._click_order_button(page):  # cart_handle_payment
  File "/home/runner/work/apic/apic/epic/src/services/bricklayer/core.py", line 456, in _click_order_button
    payment_btn.click()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13519, in click
    self._sync(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "xpath=//div[@id='webPurchaseContainer']//iframe"
============================================================
